Don't stop the postgres engine

diff --git a/jenkins-slave b/jenkins-slave
--- a/jenkins-slave
+++ b/jenkins-slave
@@ -6,11 +6,43 @@ set -e
 # (will allow for "$XYZ_DB_PASSWORD_FILE" to fill in the value of
 #  "$XYZ_DB_PASSWORD" from a file, especially for Docker's secrets feature)
 
+set_listen_addresses() {
+    sedEscapedValue="$(echo "$1" | sed 's/[\/&]/\\&/g')"
+    sed -ri "s/^#?(listen_addresses\s*=\s*)\S+/\1'$sedEscapedValue'/" "$PGDATA/postgresql.conf"
+}
+
+set_max_connections() {
+    sed -i -e"s/^max_connections = 100.*$/max_connections = 1000/" "$PGDATA/postgresql.conf"
+}
+
+enable_pg_stat_statements() {
+    echo "shared_preload_libraries = 'pg_stat_statements'" >> $PGDATA/postgresql.conf
+    echo "pg_stat_statements.max = 10000" >> $PGDATA/postgresql.conf
+    echo "pg_stat_statements.track = all" >> $PGDATA/postgresql.conf
+}
+
+file_env() {
+	local var="$1"
+	local fileVar="${var}_FILE"
+	local def="${2:-}"
+	if [ "${!var:-}" ] && [ "${!fileVar:-}" ]; then
+		echo >&2 "error: both $var and $fileVar are set (but are exclusive)"
+		exit 1
+	fi
+	local val="$def"
+	if [ "${!var:-}" ]; then
+		val="${!var}"
+	elif [ "${!fileVar:-}" ]; then
+		val="$(< "${!fileVar}")"
+	fi
+	export "$var"="$val"
+	unset "$fileVar"
+}
+
 if [ $# -eq 1 ]; then
 	# if `docker run` only has one arguments, we assume user is running alternate command like `bash` to inspect the image
 	exec "$@"
 else
-
 	# if -tunnel is not provided try env vars
 	case "$@" in
 		*"-tunnel "*) ;;
@@ -61,148 +93,91 @@ else
 		esac
 	fi
 
-	#TODO: Handle the case when the command-line and Environment variable contain different values.
-	#It is fine it blows up for now since it should lead to an error anyway.
 
+    if [ ! -d  "$PGDATA" ]; then
+        mkdir -p "$PGDATA"
+        chmod 700 "$PGDATA"
+        chown -R postgres "$PGDATA"
+    fi
+
+    chmod 700 "$PGDATA"
+    chown -R postgres "$PGDATA"
+
+    #chmod g+s /run/postgresql
+    #chown -R postgres /run/postgresql
+
+    # look specifically for PG_VERSION, as it is expected in the DB dir
+    if [ ! -s "$PGDATA/PG_VERSION" ]; then
+        gosu postgres initdb
+
+        # check password first so we can output the warning before postgres
+        # messes it up
+        if [ "$POSTGRES_PASSWORD" ]; then
+            pass="PASSWORD '$POSTGRES_PASSWORD'"
+            authMethod=md5
+        else
+            # The - option suppresses leading tabs but *not* spaces. :)
+            cat >&2 <<-'EOWARN'
+                ****************************************************
+                WARNING: No password has been set for the database.
+                         This will allow anyone with access to the
+                         Postgres port to access your database. In
+                         Docker's default configuration, this is
+                         effectively any other container on the same
+                         system.
+
+                         Use "-e POSTGRES_PASSWORD=password" to set
+                         it in "docker run".
+                ****************************************************
+EOWARN
+
+            pass=
+            authMethod=trust
+        fi
+
+        { echo; echo "host all all 0.0.0.0/0 $authMethod"; } >> "$PGDATA/pg_hba.conf"
+
+        # internal start of server in order to allow set-up using psql-client
+        # does not listen on TCP/IP and waits until start finishes
+        gosu postgres pg_ctl -D "$PGDATA" \
+            -o "-c listen_addresses=''" \
+            -w start
+
+        : ${POSTGRES_USER:=postgres}
+        : ${POSTGRES_DATABASES:=$POSTGRES_USER}
+        export POSTGRES_USER POSTGRES_DATABASES
+        for DB in $POSTGRES_DATABASES
+            do
+            if [ "$DB" != 'postgres' ]; then
+                psql --username postgres <<-EOSQL
+                    CREATE DATABASE "$DB" ;
+EOSQL
+                echo
+            fi
+        done
+
+        if [ "$POSTGRES_USER" = 'postgres' ]; then
+            op='ALTER'
+        else
+            op='CREATE'
+        fi
+
+        psql --username postgres <<-EOSQL
+            $op USER "$POSTGRES_USER" WITH SUPERUSER $pass ;
+EOSQL
+
+        echo
+
+        #gosu postgres pg_ctl -D "$PGDATA" -m fast -w start
+        set_listen_addresses '*'
+		set_max_connections
+        enable_pg_stat_statements
+
+        echo
+        echo 'PostgreSQL init process complete; ready for start up.'
+        echo
+    fi
+    
+	## Jenkins stuff
 	exec java $JAVA_OPTS $JNLP_PROTOCOL_OPTS -cp /usr/share/jenkins/slave.jar hudson.remoting.jnlp.Main -headless $TUNNEL $URL $WORKDIR $OPT_JENKINS_SECRET $OPT_JENKINS_AGENT_NAME "$@"
-
 fi
-
-file_env() {
-	local var="$1"
-	local fileVar="${var}_FILE"
-	local def="${2:-}"
-	if [ "${!var:-}" ] && [ "${!fileVar:-}" ]; then
-		echo >&2 "error: both $var and $fileVar are set (but are exclusive)"
-		exit 1
-	fi
-	local val="$def"
-	if [ "${!var:-}" ]; then
-		val="${!var}"
-	elif [ "${!fileVar:-}" ]; then
-		val="$(< "${!fileVar}")"
-	fi
-	export "$var"="$val"
-	unset "$fileVar"
-}
-
-if [ "${1:0:1}" = '-' ]; then
-	set -- postgres "$@"
-fi
-
-# allow the container to be started with `--user`
-if [ "$1" = 'postgres' ] && [ "$(id -u)" = '0' ]; then
-	mkdir -p "$PGDATA"
-	chown -R postgres "$PGDATA"
-	chmod 700 "$PGDATA"
-
-	mkdir -p /var/run/postgresql
-	chown -R postgres /var/run/postgresql
-	chmod 775 /var/run/postgresql
-
-	# Create the transaction log directory before initdb is run (below) so the directory is owned by the correct user
-	if [ "$POSTGRES_INITDB_XLOGDIR" ]; then
-		mkdir -p "$POSTGRES_INITDB_XLOGDIR"
-		chown -R postgres "$POSTGRES_INITDB_XLOGDIR"
-		chmod 700 "$POSTGRES_INITDB_XLOGDIR"
-	fi
-
-	exec su-exec postgres "$BASH_SOURCE" "$@"
-fi
-
-if [ "$1" = 'postgres' ]; then
-	mkdir -p "$PGDATA"
-	chown -R "$(id -u)" "$PGDATA" 2>/dev/null || :
-	chmod 700 "$PGDATA" 2>/dev/null || :
-
-	# look specifically for PG_VERSION, as it is expected in the DB dir
-	if [ ! -s "$PGDATA/PG_VERSION" ]; then
-		file_env 'POSTGRES_INITDB_ARGS'
-		if [ "$POSTGRES_INITDB_XLOGDIR" ]; then
-			export POSTGRES_INITDB_ARGS="$POSTGRES_INITDB_ARGS --xlogdir $POSTGRES_INITDB_XLOGDIR"
-		fi
-		eval "initdb --username=postgres $POSTGRES_INITDB_ARGS"
-
-		# check password first so we can output the warning before postgres
-		# messes it up
-		file_env 'POSTGRES_PASSWORD'
-		if [ "$POSTGRES_PASSWORD" ]; then
-			pass="PASSWORD '$POSTGRES_PASSWORD'"
-			authMethod=md5
-		else
-			# The - option suppresses leading tabs but *not* spaces. :)
-			cat >&2 <<-'EOWARN'
-				****************************************************
-				WARNING: No password has been set for the database.
-				         This will allow anyone with access to the
-				         Postgres port to access your database. In
-				         Docker's default configuration, this is
-				         effectively any other container on the same
-				         system.
-
-				         Use "-e POSTGRES_PASSWORD=password" to set
-				         it in "docker run".
-				****************************************************
-			EOWARN
-
-			pass=
-			authMethod=trust
-		fi
-
-		{
-			echo
-			echo "host all all all $authMethod"
-		} >> "$PGDATA/pg_hba.conf"
-
-		# internal start of server in order to allow set-up using psql-client
-		# does not listen on external TCP/IP and waits until start finishes
-		PGUSER="${PGUSER:-postgres}" \
-		pg_ctl -D "$PGDATA" \
-			-o "-c listen_addresses='localhost'" \
-			-w start
-
-		file_env 'POSTGRES_USER' 'postgres'
-		file_env 'POSTGRES_DB' "$POSTGRES_USER"
-
-		psql=( psql -v ON_ERROR_STOP=1 )
-
-		if [ "$POSTGRES_DB" != 'postgres' ]; then
-			"${psql[@]}" --username postgres <<-EOSQL
-				CREATE DATABASE "$POSTGRES_DB" ;
-			EOSQL
-			echo
-		fi
-
-		if [ "$POSTGRES_USER" = 'postgres' ]; then
-			op='ALTER'
-		else
-			op='CREATE'
-		fi
-		"${psql[@]}" --username postgres <<-EOSQL
-			$op USER "$POSTGRES_USER" WITH SUPERUSER $pass ;
-		EOSQL
-		echo
-
-		psql+=( --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" )
-
-		echo
-		for f in /docker-entrypoint-initdb.d/*; do
-			case "$f" in
-				*.sh)     echo "$0: running $f"; . "$f" ;;
-				*.sql)    echo "$0: running $f"; "${psql[@]}" -f "$f"; echo ;;
-				*.sql.gz) echo "$0: running $f"; gunzip -c "$f" | "${psql[@]}"; echo ;;
-				*)        echo "$0: ignoring $f" ;;
-			esac
-			echo
-		done
-
-		PGUSER="${PGUSER:-postgres}" \
-		pg_ctl -D "$PGDATA" -m fast -w stop
-
-		echo
-		echo 'PostgreSQL init process complete; ready for start up.'
-		echo
-	fi
-fi
-
-exec "$@"
